enum USER_ROLE {
  CLIENT = "CLIENT",
  PROFESSIONAL = "PROFESSIONAL",
}

enum APPOINTMENT_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELED = "CANCELED",
  COMPLETED = "COMPLETED",
}

enum PET_SIZE {
  SMALL = "SMALL",
  MEDIUM = "MEDIUM",
  LARGE = "LARGE",
}

enum SERVICE_TYPE {
  CONSULTATION = "CONSULTATION",
  VACCINATION = "VACCINATION",
  EXAM = "EXAM",
  GROOMING = "GROOMING",
  TRAINING = "TRAINING",
  BOARDING = "BOARDING",
  MICROCHIPPING = "MICROCHIPPING",
  NUTRITION = "NUTRITION",
  SURGERY = "SURGERY",
  DENTAL_CARE = "DENTAL_CARE",
  BEHAVIORAL_THERAPY = "BEHAVIORAL_THERAPY",
  OTHER = "OTHER",
}

export {
  USER_ROLE,
  APPOINTMENT_STATUS,
  PET_SIZE,
  SERVICE_TYPE
}
