enum USER_ROLE {
  CLIENT = "CLIENT",
  PROFESSIONAL = "PROFESSIONAL",
}

enum APPOINTMENT_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELED = "CANCELED",
}

enum PET_SIZE {
  SMALL = "SMALL",
  MEDIUM = "MEDIUM",
  LARGE = "LARGE",
}

enum SERVICE_TYPE {
  CONSULTATION = "CONSULTATION",
  VACCINATION = "VACCINATION",
  EXAM = "EXAM",
  OTHER = "OTHER",
}

export {
  USER_ROLE,
  APPOINTMENT_STATUS,
  PET_SIZE,
  SERVICE_TYPE
}
